# Generated by Django 5.2.1 on 2025-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='municipality',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
