# Generated by Django 5.2.1 on 2025-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
