# Generated by Django 5.2.1 on 2025-05-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_placetrigaluser_address_place_trigal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administeruser',
            name='place_to_administer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.placetrigaluser'),
        ),
    ]
