# Generated by Django 5.2.1 on 2025-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userhistory_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='comments',
            field=models.TextField(blank=True, default='Postulante archivado'),
        ),
    ]
