# Generated by Django 5.2.1 on 2025-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_administeruser_place_to_administer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp'),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
