# Generated by Django 5.2.1 on 2025-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
