# Generated by Django 5.2.1 on 2025-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userhistory_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
