# Generated by Django 5.2.1 on 2025-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_whatsappuser_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='cv_full_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
