# Generated by Django 5.2.1 on 2025-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_whatsappuser_cv_full_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappuser',
            name='cv_full_url',
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='work_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
