# Generated by Django 5.2.1 on 2025-06-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_whatsappuser_approved_whatsappuser_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappuser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='whatsappuser',
            name='archived',
        ),
    ]
