# Generated by Django 5.2.1 on 2025-05-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_whatsappuser_cv_full_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='document',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='work_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
