# Generated by Django 5.2.1 on 2025-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_whatsappuser_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
