# Generated by Django 5.2.1 on 2025-06-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_whatsappuser_approved_whatsappuser_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='archived',
        ),
    ]
