# Generated by Django 5.2.1 on 2025-05-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0001_initial'),
        ('users', '0003_alter_administeruser_place_to_administer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.placetrigaluser'),
        ),
        migrations.AlterField(
            model_name='messageaiuser',
            name='answer',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='messageaiuser',
            name='ask',
            field=models.CharField(max_length=300),
        ),
    ]
