# Generated by Django 5.2.1 on 2025-05-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0002_messagetemplate_place_alter_messageaiuser_answer_and_more'),
        ('users', '0007_alter_whatsappuser_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='description',
            field=models.TextField(default='...', max_length=2000),
        ),
        migrations.CreateModel(
            name='UploadExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.placetrigaluser')),
            ],
        ),
    ]
